### ISSUE TITLE
CSV output is broken.

### ISSUE THREAD

**Issue by lcreid** [weenhanceit/gaapi#7]
CSV output is broken:

```
/var/lib/gems/2.3.0/gems/gaapi-0.4.2/lib/gaapi/report.rb:45:in `totals': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/gaapi-0.4.2/lib/gaapi/response.rb:38:in `block (2 levels) in csv'
	from /var/lib/gems/2.3.0/gems/gaapi-0.4.2/lib/gaapi/response.rb:27:in `each'
	from /var/lib/gems/2.3.0/gems/gaapi-0.4.2/lib/gaapi/response.rb:27:in `block in csv'
	from /usr/lib/ruby/2.3.0/csv.rb:1166:in `generate'
	from /var/lib/gems/2.3.0/gems/gaapi-0.4.2/lib/gaapi/response.rb:26:in `csv'
	from /var/lib/gems/2.3.0/gems/gaapi-0.4.2/lib/gaapi/main.rb:40:in `call'
	from /var/lib/gems/2.3.0/gems/gaapi-0.4.2/bin/gaapi:7:in `<top (required)>'
	from /usr/local/bin/gaapi:23:in `load'
	from /usr/local/bin/gaapi:23:in `<main>'
```

**Comment by lcreid** [comment]
Fixed by 38319c8d8b1fad3340ae471e2af854bfd6878c12.
